export const data = [
  {
    _id: '65dc5025b6fc0ca67d462ca1',
    index: 0,
    date: '2024-02-24',
    todoEvents: 2,
    finishedEvents: 1,
    signLists: [
      {
        name: 'Fowler Powers',
        gender: 'male',
        dept: 'ORBIFLEX',
        email: 'fowlerpowers@orbiflex.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Jodie Mejia',
        gender: 'female',
        dept: 'RUBADUB',
        email: 'jodiemejia@rubadub.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Mckinney Campbell',
        gender: 'male',
        dept: 'MEDESIGN',
        email: 'mckinneycampbell@medesign.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Tucker Ballard',
        gender: 'male',
        dept: 'ROCKABYE',
        email: 'tuckerballard@rockabye.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Howe Mays',
        gender: 'male',
        dept: 'TELLIFLY',
        email: 'howemays@tellifly.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Anna Espinoza',
        gender: 'female',
        dept: 'PUSHCART',
        email: 'annaespinoza@pushcart.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Hattie Boone',
        gender: 'female',
        dept: 'MICRONAUT',
        email: 'hattieboone@micronaut.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Dotson Curtis',
        gender: 'male',
        dept: 'ZAYA',
        email: 'dotsoncurtis@zaya.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Cleveland Mayer',
        gender: 'male',
        dept: 'ATOMICA',
        email: 'clevelandmayer@atomica.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Kristin Park',
        gender: 'female',
        dept: 'HOPELI',
        email: 'kristinpark@hopeli.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Susanna Barker',
        gender: 'female',
        dept: 'ZYTREX',
        email: 'susannabarker@zytrex.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Cameron Hays',
        gender: 'male',
        dept: 'ZIDOX',
        email: 'cameronhays@zidox.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Norris Castaneda',
        gender: 'male',
        dept: 'JIMBIES',
        email: 'norriscastaneda@jimbies.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Nicholson Hancock',
        gender: 'male',
        dept: 'JASPER',
        email: 'nicholsonhancock@jasper.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Aurora Aguirre',
        gender: 'female',
        dept: 'ZIPAK',
        email: 'auroraaguirre@zipak.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Walter Golden',
        gender: 'male',
        dept: 'EXTRAWEAR',
        email: 'waltergolden@extrawear.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Patton Estes',
        gender: 'male',
        dept: 'ESSENSIA',
        email: 'pattonestes@essensia.com',
        onDuty: false,
        offDuty: true,
      },
    ],
  },
  {
    _id: '65dc50252629c88b7c23c295',
    index: 1,
    date: '2024-02-25',
    todoEvents: 1,
    finishedEvents: 1,
    signLists: [
      {
        name: 'Ortega Lamb',
        gender: 'male',
        dept: 'TERRAGO',
        email: 'ortegalamb@terrago.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Angelique Thomas',
        gender: 'female',
        dept: 'BLANET',
        email: 'angeliquethomas@blanet.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Ruiz Cooley',
        gender: 'male',
        dept: 'SNOWPOKE',
        email: 'ruizcooley@snowpoke.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Adela Wright',
        gender: 'female',
        dept: 'COMTENT',
        email: 'adelawright@comtent.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Tania Mcintosh',
        gender: 'female',
        dept: 'MOREGANIC',
        email: 'taniamcintosh@moreganic.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Angelica Charles',
        gender: 'female',
        dept: 'EARWAX',
        email: 'angelicacharles@earwax.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Herminia Shaw',
        gender: 'female',
        dept: 'OLUCORE',
        email: 'herminiashaw@olucore.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Alicia Larson',
        gender: 'female',
        dept: 'TUBESYS',
        email: 'alicialarson@tubesys.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Wood Carr',
        gender: 'male',
        dept: 'IZZBY',
        email: 'woodcarr@izzby.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Alfreda Hatfield',
        gender: 'female',
        dept: 'QABOOS',
        email: 'alfredahatfield@qaboos.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Kaitlin Kaufman',
        gender: 'female',
        dept: 'NEOCENT',
        email: 'kaitlinkaufman@neocent.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Joyce Hayes',
        gender: 'male',
        dept: 'ROCKLOGIC',
        email: 'joycehayes@rocklogic.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Hardin Giles',
        gender: 'male',
        dept: 'RETRACK',
        email: 'hardingiles@retrack.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Chavez Cabrera',
        gender: 'male',
        dept: 'INTERLOO',
        email: 'chavezcabrera@interloo.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Glass Shepard',
        gender: 'male',
        dept: 'KRAGGLE',
        email: 'glassshepard@kraggle.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Dawson Barber',
        gender: 'male',
        dept: 'BESTO',
        email: 'dawsonbarber@besto.com',
        onDuty: false,
        offDuty: false,
      },
    ],
  },
  {
    _id: '65dc5025ccba58fc9f5c579a',
    index: 2,
    date: '2024-02-26',
    todoEvents: 3,
    finishedEvents: 2,
    signLists: [
      {
        name: 'Rose Newman',
        gender: 'female',
        dept: 'ZOLAR',
        email: 'rosenewman@zolar.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Wiggins Castillo',
        gender: 'male',
        dept: 'GEEKETRON',
        email: 'wigginscastillo@geeketron.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Marietta Bray',
        gender: 'female',
        dept: 'ORBEAN',
        email: 'mariettabray@orbean.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Toni Mcdaniel',
        gender: 'female',
        dept: 'OTHERWAY',
        email: 'tonimcdaniel@otherway.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Leon Burt',
        gender: 'male',
        dept: 'ZENOLUX',
        email: 'leonburt@zenolux.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Sanders Webster',
        gender: 'male',
        dept: 'EVIDENDS',
        email: 'sanderswebster@evidends.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Marylou Franco',
        gender: 'female',
        dept: 'NURPLEX',
        email: 'maryloufranco@nurplex.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Puckett Fernandez',
        gender: 'male',
        dept: 'BEDLAM',
        email: 'puckettfernandez@bedlam.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Buckley Cobb',
        gender: 'male',
        dept: 'UNIA',
        email: 'buckleycobb@unia.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Sherman Vazquez',
        gender: 'male',
        dept: 'ISOLOGIA',
        email: 'shermanvazquez@isologia.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Stein Rodgers',
        gender: 'male',
        dept: 'VIXO',
        email: 'steinrodgers@vixo.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Angelina Bentley',
        gender: 'female',
        dept: 'BUGSALL',
        email: 'angelinabentley@bugsall.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Castaneda Marquez',
        gender: 'male',
        dept: 'SARASONIC',
        email: 'castanedamarquez@sarasonic.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Margret Whitehead',
        gender: 'female',
        dept: 'SHOPABOUT',
        email: 'margretwhitehead@shopabout.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Jacqueline Manning',
        gender: 'female',
        dept: 'PORTALINE',
        email: 'jacquelinemanning@portaline.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Lorna Finch',
        gender: 'female',
        dept: 'ADORNICA',
        email: 'lornafinch@adornica.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Sheri Williams',
        gender: 'female',
        dept: 'CORMORAN',
        email: 'sheriwilliams@cormoran.com',
        onDuty: false,
        offDuty: false,
      },
    ],
  },
  {
    _id: '65dc502527848e5cbc7af78d',
    index: 3,
    date: '2024-02-27',
    todoEvents: 2,
    finishedEvents: 2,
    signLists: [
      {
        name: 'Randi Reilly',
        gender: 'female',
        dept: 'BRAINQUIL',
        email: 'randireilly@brainquil.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Ines Baird',
        gender: 'female',
        dept: 'EXERTA',
        email: 'inesbaird@exerta.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Beverley Reese',
        gender: 'female',
        dept: 'ENTHAZE',
        email: 'beverleyreese@enthaze.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'David Hansen',
        gender: 'male',
        dept: 'FREAKIN',
        email: 'davidhansen@freakin.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Lucile Lowe',
        gender: 'female',
        dept: 'NIKUDA',
        email: 'lucilelowe@nikuda.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Goldie Holloway',
        gender: 'female',
        dept: 'ACCUFARM',
        email: 'goldieholloway@accufarm.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Hartman Mcneil',
        gender: 'male',
        dept: 'GEOFORMA',
        email: 'hartmanmcneil@geoforma.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Lucy Sandoval',
        gender: 'female',
        dept: 'ZILLAR',
        email: 'lucysandoval@zillar.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Coffey Sloan',
        gender: 'male',
        dept: 'SCENTRIC',
        email: 'coffeysloan@scentric.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Brandi Lindsay',
        gender: 'female',
        dept: 'BALUBA',
        email: 'brandilindsay@baluba.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Celia Ball',
        gender: 'female',
        dept: 'RETROTEX',
        email: 'celiaball@retrotex.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Dalton Randolph',
        gender: 'male',
        dept: 'INTRADISK',
        email: 'daltonrandolph@intradisk.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Hurley Bennett',
        gender: 'male',
        dept: 'UXMOX',
        email: 'hurleybennett@uxmox.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Dixie Peterson',
        gender: 'female',
        dept: 'COSMOSIS',
        email: 'dixiepeterson@cosmosis.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Klein Whitfield',
        gender: 'male',
        dept: 'UNEEQ',
        email: 'kleinwhitfield@uneeq.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Patterson Kramer',
        gender: 'male',
        dept: 'ECSTASIA',
        email: 'pattersonkramer@ecstasia.com',
        onDuty: false,
        offDuty: true,
      },
    ],
  },
  {
    _id: '65dc502558ab9e5c248ab9b0',
    index: 4,
    date: '2024-02-28',
    todoEvents: 0,
    finishedEvents: 0,
    signLists: [
      {
        name: 'Madeline Odonnell',
        gender: 'female',
        dept: 'HOUSEDOWN',
        email: 'madelineodonnell@housedown.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Essie Flynn',
        gender: 'female',
        dept: 'SENSATE',
        email: 'essieflynn@sensate.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Oliver Jenkins',
        gender: 'male',
        dept: 'ORBAXTER',
        email: 'oliverjenkins@orbaxter.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Tiffany Sanders',
        gender: 'female',
        dept: 'MEDIFAX',
        email: 'tiffanysanders@medifax.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Iris Grant',
        gender: 'female',
        dept: 'IDEALIS',
        email: 'irisgrant@idealis.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Mills Knight',
        gender: 'male',
        dept: 'PODUNK',
        email: 'millsknight@podunk.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'April Stark',
        gender: 'female',
        dept: 'ZYTREK',
        email: 'aprilstark@zytrek.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Blake Hull',
        gender: 'male',
        dept: 'CANOPOLY',
        email: 'blakehull@canopoly.com',
        onDuty: false,
        offDuty: false,
      },
      {
        name: 'Jefferson Moody',
        gender: 'male',
        dept: 'MACRONAUT',
        email: 'jeffersonmoody@macronaut.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Serena Harrell',
        gender: 'female',
        dept: 'RONELON',
        email: 'serenaharrell@ronelon.com',
        onDuty: false,
        offDuty: true,
      },
      {
        name: 'Sloan Hendrix',
        gender: 'male',
        dept: 'SHEPARD',
        email: 'sloanhendrix@shepard.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Krista Sheppard',
        gender: 'female',
        dept: 'ISOSURE',
        email: 'kristasheppard@isosure.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Whitney Avila',
        gender: 'male',
        dept: 'CENTURIA',
        email: 'whitneyavila@centuria.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Emerson Buckley',
        gender: 'male',
        dept: 'INSURESYS',
        email: 'emersonbuckley@insuresys.com',
        onDuty: true,
        offDuty: false,
      },
      {
        name: 'Nina Pitts',
        gender: 'female',
        dept: 'PARCOE',
        email: 'ninapitts@parcoe.com',
        onDuty: true,
        offDuty: true,
      },
      {
        name: 'Ashley Randall',
        gender: 'male',
        dept: 'UNISURE',
        email: 'ashleyrandall@unisure.com',
        onDuty: true,
        offDuty: true,
      },
    ],
  },
];
